# This config file contains options specific to Autonomous Operations
# mode with Consul. In order for these options to take effect, the path to
# this file must be specified as the `--consul-config` argument of the
# `cbes-consul` command.

[consul]
  # Optional ACL Token to include in all Consul requests. If the value is an
  # empty string, the token is determined by the Consul agent configuration.
  #
  # The pre-populated value gets the token from the "CBES_CONSUL_ACL_TOKEN"
  # environment variable, falling back to empty string if the environment
  # variable is not present.
  aclToken = '${CBES_CONSUL_ACL_TOKEN:}'
