[group]
  name = 'first-group'

[group.static]
  memberNumber = 1 # A value from 1 to 'totalMembers', inclusive.
  totalMembers = 1

# Performance metrics may be written to a log file and/or exposed via HTTP.
[metrics]
  httpPort = 31415 # Positive = fixed, 0 = ephemeral, -1 = disable HTTP server
  logInterval = '1m' # Set to '0m' to disable metrics logging

# If you decide not to enable secure connections, you can ignore this section.
[truststore]
  path = 'path/to/truststore'
  pathToPassword = 'secrets/truststore-password.toml'

[couchbase]
  hosts = ['${CB_HOST:localhost}']
  network = 'auto'
  bucket = '${CB_BUCKET:default}'
  metadataBucket = ''
  username = '${CB_USER:Admin}'
  pathToPassword = 'secrets/couchbase-password.toml'
  secureConnection = false

# Options for the Couchbase Database Change Protocol (DCP).
[couchbase.dcp]
  compression = true
  flowControlBuffer = '128mb'
  persistencePollingInterval = '100ms'

[elasticsearch]
  hosts = ['${ES_HOST:localhost}']
  username = '${ES_USER:elastic}'
  pathToPassword = 'secrets/elasticsearch-password.toml'
  secureConnection = false

[elasticsearch.bulkRequestLimits]
  bytes = '10mb'
  actions = 1000
  timeout = '1m'
  concurrentRequests = 2

[elasticsearch.docStructure]
  metadataFieldName = 'meta'
  documentContentAtTopLevel = false
  wrapCounters = false

# The values in this section may be overridden by specific type definitions.
[elasticsearch.typeDefaults]
  index = ''
  pipeline = ''
  typeName = '_doc'
  ignore = false
  ignoreDeletes = false

[[elasticsearch.type]]
  prefix = '_sync:' # Couchbase Sync Gateway metadata
  ignore = true

[[elasticsearch.type]]
  prefix = '${ES_REP_PREFIX:replicate.*}'
  index = '${ES_INDEX:default}'
  pipeline = ''

# When Elasticsearch rejects a document (usually due to a type mapping error)
# a rejection log entry document is written to Elasticsearch. The log entry's
# document ID is the ID of the rejected Couchbase document. The log entry's
# content has the following fields:
#   "index"  - (string) name of the index the connector tried to write to
#   "type"   - (string) document type name used for the write attempt
#   "action" - (string) failed action type ("INDEX" or "DELETE")
#   "error"  - (string) error message received from Elasticsearch
[elasticsearch.rejectionLog]
  index = 'cbes-rejects'
  typeName = '_doc' # For ES 5.x remove leading underscore!
